### ISSUE TITLE
Please organize the list like you would for English lab.

### ISSUE THREAD

**Issue by hahaysh** [MicrosoftLearning/AZ500-AzureSecurityTechnologies.ko-kr#13]
Description of issue

Practice details are not organized.
There are too many duplicate lab.
Please organize the list like you would for English lab.

**Comment by olprod** [comment]
Hello contributor,

Thank you for your contribution! We are processing your suggestions and we will update you shortly.   

Kind regards,  

Microsoft Worldwide Learning Team

**Comment by stonezy123** [comment]
The loc repo was synced with source repo.
